### ISSUE TITLE
Failed Download on script/run at Windows XP 32Bits

### ISSUE THREAD

**Issue by fellix** [maccman/bowline#11]
I'm using Windows XP 32 bits and ruby 1.8.7, when i type ruby script\run I've get

http://img820.imageshack.us/img820/566/vowline.jpg

**Comment by maccman** [comment]
If you look at the README you'll see that Windows isn't supported yet

**Comment by fellix** [comment]
Shit, Sorry, I'm not read the README. Can I help to integrate with windows?

**Comment by maccman** [comment]
That would be brilliant - basically this file needs implementing http://github.com/maccman/bowline-desktop/blob/master/bowline/bowline_webkit_win.cpp
