### ISSUE TITLE
undefined method `setup' for Bundler:Module

### ISSUE THREAD

**Issue by elia** [maccman/bowline#12]
I not really sure if this issue is about bowline or bowline-bundler (which sources I've searched without success for the setup method)... but to start I'll put this here

```
> ./script/run 
/Users/Elia/Desktop/tasks/config/boot.rb:13:in `<top (required)>': undefined method `setup' for Bundler:Module (NoMethodError)
from ./script/run:2:in `require'
from ./script/run:2:in `<main>'
```

I'm using ruby 1.9.1 (ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-darwin10.3.0])

**Comment by maccman** [comment]
As it mentions in the README, you need to run bowline-bundle

**Comment by elia** [comment]
Thanks for the patience :)

**Comment by ghost** [comment]
yeah but when you run bownline-bundle you get bunch of errors
