### ISSUE TITLE
`chmod': No such file or directory

### ISSUE THREAD

**Issue by huacnlee** [maccman/bowline#14]
hsli@hs-li:~/work$ bowline-gen app simple
Generating with app generator:
     [ADDED]  .gitignore
     [ADDED]  public/icon.png
/usr/lib/ruby/1.8/fileutils.rb:1217:in `chmod': No such file or directory - /home/hsli/work/simple/script (Errno::ENOENT)
    from /usr/lib/ruby/1.8/fileutils.rb:1217:in`chmod'
    from /usr/lib/ruby/1.8/fileutils.rb:895:in `chmod_R'
    from /usr/lib/ruby/1.8/fileutils.rb:1325:in`traverse'
    from /usr/lib/ruby/1.8/fileutils.rb:893:in `chmod_R'
    from /usr/lib/ruby/1.8/fileutils.rb:892:in`each'
    from /usr/lib/ruby/1.8/fileutils.rb:892:in `chmod_R'
    from /usr/lib/ruby/gems/1.8/gems/bowline-0.9.3/bin/../lib/bowline/generators.rb:60:in`invoke!'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:102:in `step_through_templates'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:84:in`each'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:84:in `step_through_templates'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:75:in`run'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/manifold.rb:24:in `run'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/manifold.rb:80:in`run_cli'
    from /usr/lib/ruby/gems/1.8/gems/bowline-0.9.3/bin/bowline-gen:6
    from /usr/bin/bowline-gen:19:in `load'
    from /usr/bin/bowline-gen:19

**Comment by maccman** [comment]
Can you give me some information about your environment?

**Comment by maccman** [comment]
No, not at all. Your ruby version, your ruby gems version, what os you're using etc.

**Comment by huacnlee** [comment]
I am use bowline on Ubuntu 10.04
hsli@hs-li:~/work$ ruby -v
ruby 1.8.7 (2010-01-10 patchlevel 249) [i486-linux
hsli@hs-li:~/work$ gem -v
1.3.6

**Comment by huacnlee** [comment]
Give you detail message:

hsli@hs-li:~/work$ bowline-gen app simple --debug
Generating with app generator:
 [IDENTICAL]  .gitignore
 [IDENTICAL]  public/icon.png
/usr/lib/ruby/1.8/fileutils.rb:1217:in `chmod': No such file or directory - /home/hsli/work/simple/script (Errno::ENOENT)
    from /usr/lib/ruby/1.8/fileutils.rb:1217:in`chmod'
    from /usr/lib/ruby/1.8/fileutils.rb:895:in `chmod_R'
    from /usr/lib/ruby/1.8/fileutils.rb:1325:in`traverse'
    from /usr/lib/ruby/1.8/fileutils.rb:893:in `chmod_R'
    from /usr/lib/ruby/1.8/fileutils.rb:892:in`each'
    from /usr/lib/ruby/1.8/fileutils.rb:892:in `chmod_R'
    from /usr/lib/ruby/gems/1.8/gems/bowline-0.9.3/bin/../lib/bowline/generators.rb:60:in`invoke!'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:102:in `step_through_templates'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:84:in`each'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:84:in `step_through_templates'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/generator.rb:75:in`run'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/cli/manifold.rb:24:in `run'
    from /usr/lib/ruby/gems/1.8/gems/templater-1.0.0/lib/templater/manifold.rb:80:in`run_cli'
    from /usr/lib/ruby/gems/1.8/gems/bowline-0.9.3/bin/bowline-gen:6
    from /usr/bin/bowline-gen:19:in `load'
    from /usr/bin/bowline-gen:19

**Comment by btelles** [comment]
Hi guys, I'm experiencing the same thing. if you need any more details, just let me know.

**Comment by maccman** [comment]
What ruby version are you using btelles?

**Comment by btelles** [comment]
Yup...figured it out. I switched to Ruby 1.9.1...but now Rice won't compile, and I think you had a bug regarding that compilation in late June. 

I get:

/home/.../.rvm/rubies/ruby-1.9.1-p378/bin/ruby extconf.rb
sh: Can't open configure

Any idea what that could be? (sorry if this is the wrong forum for that question)
