### ISSUE TITLE
undefined method `autoload_paths='

### ISSUE THREAD

**Issue by masterkain** [maccman/bowline#17]
Hello,
I'm using RVM and bowline/bowline-bundler (both latest git built with rake install).

ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-darwin10.4.0]

**\* LOCAL GEMS ***

activemodel (3.0.0.beta4)
activesupport (3.0.0.beta4)
bowline (0.9.3)
bowline-bundler (0.0.4)
builder (2.1.2)
diff-lcs (1.1.2)
extlib (0.9.15)
git (1.2.5)
highline (1.5.2)
i18n (0.4.1)
jeweler (1.4.0)
json_pure (1.4.3)
rake (0.8.7)
rdoc (2.5.9)
rubyforge (2.0.4)
rubygems-update (1.3.7)
rubyzip2 (2.0.1)
supermodel (0.1.3)
templater (1.0.0)
tzinfo (0.3.22)

This is the trace I get:
http://pastie.org/1043272

**Comment by maccman** [comment]
You need to use ActiveSupport 3

**Comment by masterkain** [comment]
sorry, but unless I'm missing something I'm using it, 3.0.0.beta4

are special steps/versions needed?

**Comment by maccman** [comment]
My bad, it's in the Rails master repo - you'll need to install those gems manually. The next Rails beta is not too far off which will make things easier.
