### ISSUE TITLE
no such file to load -- active_support/core_ext/object/misc

### ISSUE THREAD

**Issue by henningthies** [maccman/bowline#18]
hi,
I wanted to try out with bowline and get this error while executing bowline-gen app helloworld.

I have rvm and installed a fresh version of ruby 1.9.2-preview1. And sudo install bowline.

System:
OSX 10.5.8
rvm 0.1.26
ruby 1.9.2dev

installed gems:

activemodel (3.0.0.rc)
activesupport (3.0.0.rc)
bowline (0.9.3)
bowline-bundler (0.0.4)
builder (2.1.2)
diff-lcs (1.1.2)
extlib (0.9.15)
highline (1.6.1)
i18n (0.4.1)
rake (0.8.7)
rdoc (2.5.9)
rubygems-update (1.3.7)
rubyzip2 (2.0.1)
supermodel (0.1.3)
templater (1.0.0)

I'm not sure if its a problem using rvm with bowline. 

Henning

Errorlog:
/Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require': no such file to load -- active_support/core_ext/object/misc (LoadError)
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in`block in require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in`new_constants_in'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in`require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/supermodel-0.1.3/lib/supermodel.rb:12:in `<top (required)>'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in`require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `block in require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in`block in load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in `new_constants_in'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in`load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline/app_config.rb:1:in`<top (required)>'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in`block in require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in`new_constants_in'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in`require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline.rb:55:in `<top (required)>'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/bin/bowline-gen:3:in`require'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/bin/bowline-gen:3:in `<top (required)>'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/bin/bowline-gen:19:in`load'
    from /Users/henningthies/.rvm/gems/ruby-1.9.2-preview1/bin/bowline-gen:19:in `<main>'

**Comment by maccman** [comment]
If you look at the stack trace, you'll see that the error is actually in SuperModel.

I've fixed it in SuperModel's master.

**Comment by toovy** [comment]
Hi maccman,

I've got the same error, then I've manually update my gem source from the supermodel master, used bowline-gen to generate the app (now works fine), but after bundling and running the "hello world" app I get the same stack trace agian. So I guess the bundling takes some remote source of supermodel?!

Best Regards,
Tobias

**Comment by maccman** [comment]
Are you specifying the git repo of SuperModel in you Gemfile?

I'll release a new version soon anyway.

**Comment by henningthies** [comment]
I downloaded the repo and used the jeweler gem to build the gem local and install it. works fine.
