### ISSUE TITLE
App will not run

### ISSUE THREAD

**Issue by ntodd** [maccman/bowline#2]
script/run fails out with "Couldn't determine your source distribution for packaging runtime version 0.4.4. Please specify."

**Comment by ntodd** [comment]
also rake gems:sync fails with "Cannot find bowline = 0.4.6".  Figured it was likely related.

**Comment by maccman** [comment]
Uninstall the rubyforge version of Bowline - just use the github one

**Comment by maccman** [comment]
To fix script/run find out what version of Titanium you've got, and then change the version numbers in config/manifest

**Comment by ntodd** [comment]
Not currently installed.

Edit: I'll give the config/manifest a shot and let you know.

**Comment by maccman** [comment]
Ok, delete the vendor dir, and give gems:sync another go

**Comment by maccman** [comment]
Any luck?

**Comment by ntodd** [comment]
Sorry, been in meetings.  I'll try later tonight or tomorrow and let you know.  Thanks.

**Comment by ntodd** [comment]
Sorry it took so long.  Still having issues:

http://gist.github.com/29e00d0d52459075252d

**Comment by maccman** [comment]
Rebuild the gem from github, and set the config variable titanium_version to whatever titanium version you're using. Try it with a completely new app.
