### ISSUE TITLE
Still fails to run.  My first bug was closed

### ISSUE THREAD

**Issue by os-hybrid** [maccman/bowline#23]
I re-did everything and re downloaded the gem and made sure "tzinfo" was installed.  the Gem that was re-downloaded was 0.9.3 again.  Should this not be 0.9.4 or should I use the --pre option?

The scripts files appear to be ganged to the new 'require' though:

localhost:helloword Brad$ bowline-bundle
Calculating dependencies...
Updating source: http://rubygems.org
Updating source: http://gems.rubyforge.org
/Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/bowline-bundler-0.0.4/lib/bowline/bundler/resolver.rb:115:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
Done.
localhost:helloword Brad$ ./script/run
/Users/Brad/helloword/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Setting up Bowline. This could take a while...
/Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:113:in `set_autoload_paths': undefined method`load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:335:in `process'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in`run'
    from /Users/Brad/helloword/config/environment.rb:4:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in`call'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in`each'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `execute'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:595:in`block in invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in`invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:605:in `block in invoke_prerequisites'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in`each'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in `invoke_prerequisites'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:594:in`block in invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in`invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:581:in `invoke'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in`block in load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
    from ./script/run:3:in`<main>'
localhost:helloword Brad$

**Comment by maccman** [comment]
Download the git repo, build the gem, install that.

**Comment by os-hybrid** [comment]
I was still using the old one.
But I still get a fail do to an issue in config/boot

APP_ROOT = File.expand_path(File.join(File.dirname(**FILE**), "..")) unless defined?(APP_ROOT)

localhost:helloworld Brad$ ./script/run
/Users/Brad/helloworld/config/boot.rb:13:in `<top (required)>': undefined method`setup' for Bundler:Module (NoMethodError)
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./script/run:2:in `<main>'

Are we missing a required?

**Comment by os-hybrid** [comment]
Still got problems but it is getting further... Hmm no way to enclose a text.  Ok got to copy and paste here...

localhost:~ Brad$ bowline-gen app helloworld
Generating with app generator:
     [ADDED]  vendor
     [ADDED]  lib
     [ADDED]  db
     [ADDED]  build
     [ADDED]  log
     [ADDED]  public
     [ADDED]  app
     [ADDED]  app/models
     [ADDED]  app/binders
     [ADDED]  app/helpers
     [ADDED]  app/windows
     [ADDED]  config
     [ADDED]  config/initializers
     [ADDED]  config/first_run
     [ADDED]  app_first_run
     [ADDED]  Rakefile
     [ADDED]  Gemfile
     [ADDED]  public/index.html
     [ADDED]  public/javascripts/application.js
     [ADDED]  public/stylesheets/application.css
     [ADDED]  script/build
     [ADDED]  script/console
     [ADDED]  script/generate
     [ADDED]  script/init
     [ADDED]  script/run
     [ADDED]  config/environment.rb
     [ADDED]  config/environments/development.rb
     [ADDED]  config/environments/production.rb
     [ADDED]  .gitignore
     [ADDED]  public/icon.png
     [ADDED]  script
     [ADDED]  public/javascripts/jquery.js
     [ADDED]  public/javascripts/jquery.chain.js
     [ADDED]  public/javascripts/superclass.js
     [ADDED]  public/javascripts/bowline.js
     [ADDED]  public/javascripts/bowline.chain.js
     [ADDED]  app/windows/main_window.rb
     [ADDED]  config/application.yml
     [ADDED]  config/database.yml
     [ADDED]  config/boot.rb
     [ADDED]  README
localhost:~ Brad$ cd helloworld/
localhost:helloworld Brad$ bowline-bundle 
Calculating dependencies...
Updating source: http://rubygems.org
Updating source: http://gems.rubyforge.org
/Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/bowline-bundler-0.0.4/lib/bowline/bundler/resolver.rb:115:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
Caching: activemodel-3.0.0.gem
Caching: activesupport-3.0.0.gem
Caching: bowline-0.9.3.gem
Caching: bowline-bundler-0.0.4.gem
Caching: builder-2.1.2.gem
Caching: diff-lcs-1.1.2.gem
Caching: extlib-0.9.15.gem
Caching: highline-1.6.1.gem
Caching: i18n-0.4.1.gem
Caching: rubyzip2-2.0.1.gem
Caching: supermodel-0.1.4.gem
Caching: templater-1.0.0.gem
Caching: tzinfo-0.3.23.gem
Installing tzinfo (0.3.23)
Installing extlib (0.9.15)
Installing highline (1.6.1)
Installing diff-lcs (1.1.2)
Installing templater (1.0.0)
Installing bowline-bundler (0.0.4)
Installing i18n (0.4.1)
Installing builder (2.1.2)
Installing supermodel (0.1.4)
Installing rubyzip2 (2.0.1)
Installing activesupport (3.0.0)
Installing activemodel (3.0.0)
Installing bowline (0.9.3)
    **************************************************

```
  Thank you for installing Bowline.

  If you're on Linux, please install the WebKit library:
    sudo apt-get install libwebkit-dev

**************************************************
```

Done.
localhost:helloworld Brad$ ls
Gemfile     app     build       lib     script
README      app_first_run   config      log     vendor
Rakefile    bin     db      public
localhost:helloworld Brad$ ./script/run
/Users/Brad/helloworld/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Setting up Bowline. This could take a while...
Retrieving http://bowline.s3.amazonaws.com/osx/bowline-desktop.zip
:              100% |oooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:04
Extracting bowline-desktop.zip
Retrieving http://bowline.s3.amazonaws.com/osx/libs.zip
:              100% |oooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:10
Extracting libs.zip
    no such file to load -- gem_release
/Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in `require'
    /Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in`<top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in `load'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in`block in <top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in `each'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in`<top (required)>'
    /Users/Brad/helloworld/config/boot.rb:3:in `require'
    /Users/Brad/helloworld/config/boot.rb:3:in`<top (required)>'
    /Users/Brad/helloworld/script/init:2:in `require'
    /Users/Brad/helloworld/script/init:2:in`<top (required)>'
2010-09-21 13:11:30.424 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb17fe0 of class WebView autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.426 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb10d80 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.426 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb1e5e0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.426 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb1dea0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.427 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb1e4c0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.427 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb014b0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.427 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb09880 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.427 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb098a0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 13:11:30.427 bowline-desktop[82539:1f07] **\* __NSAutoreleaseNoPool(): Object 0xb1e4e0 of class __NSFastEnumerationEnumerator autoreleased with no pool in place - just leaking
localhost:helloworld Brad$

**Comment by os-hybrid** [comment]
I use ruby 1.9.2 p0 and RVM

Most importantly I have no idea why github keeps moving my Bug report to "Closed" instead of keeping it on "Open"

**Comment by os-hybrid** [comment]
ran it again in the same directory as the gem was built.  Got more or less the same thing... OS X 10.6.4 ... Latest MacBook Pro

Installing activemodel (3.0.0)
Installing bowline (0.9.3)
    **************************************************

```
  Thank you for installing Bowline.

  If you're on Linux, please install the WebKit library:
    sudo apt-get install libwebkit-dev

**************************************************
```

Done.
localhost:helloworld Brad$ ./script/run 
/Users/Brad/Desktop/bowline/helloworld/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
    no such file to load -- gem_release
/Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in `require'
    /Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in`<top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in `load'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in`block in <top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in `each'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in`<top (required)>'
    /Users/Brad/Desktop/bowline/helloworld/config/boot.rb:3:in `require'
    /Users/Brad/Desktop/bowline/helloworld/config/boot.rb:3:in`<top (required)>'
    /Users/Brad/Desktop/bowline/helloworld/script/init:2:in `require'
    /Users/Brad/Desktop/bowline/helloworld/script/init:2:in`<top (required)>'
2010-09-21 17:42:40.813 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0xb1ec80 of class WebView autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.814 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x137027c0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.815 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x137034b0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.815 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x13702480 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.815 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x13703530 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.815 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x137041b0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.815 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x13703670 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.816 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x13704020 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-21 17:42:40.816 bowline-desktop[83378:1c07] **\* __NSAutoreleaseNoPool(): Object 0x13704280 of class __NSFastEnumerationEnumerator autoreleased with no pool in place - just leaking
localhost:helloworld Brad$

**Comment by pushcx** [comment]
maccman: Any reason not to cut a point release with this and the other couple small bugfixes? This is not the first time the bug's been reported, and I almost duped it myself.

**Comment by os-hybrid** [comment]
"Any reason not to cut a point release with this"....  not sure if I understood... so I will be waiting till the next release, is that it?

**Comment by os-hybrid** [comment]
Just used the updated 0.9.3 gem available today.... But still having the same problem.

require File.join(File.dirname(File.expand_path(**FILE**)), *%w[.. config boot])

**Comment by os-hybrid** [comment]
Oops sorry wrong copy and paste... Here it is...

```
**************************************************

  Thank you for installing Bowline.

  If you're on Linux, please install the WebKit library:
    sudo apt-get install libwebkit-dev

**************************************************
```

Done.
localhost:helloworld Brad$ ./script/run
/Users/Brad/helloworld/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
    no such file to load -- gem_release
/Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in `require'
    /Users/Brad/.rvm/gems/ruby-1.9.2-p0/gems/gem-release-0.0.12/lib/rubygems_plugin.rb:2:in`<top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in `load'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1079:in`block in <top (required)>'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in `each'
    /Users/Brad/.bowline/libs/rubylib/1.9.1/rubygems.rb:1071:in`<top (required)>'
    /Users/Brad/helloworld/config/boot.rb:3:in `require'
    /Users/Brad/helloworld/config/boot.rb:3:in`<top (required)>'
    /Users/Brad/helloworld/script/init:2:in `require'
    /Users/Brad/helloworld/script/init:2:in`<top (required)>'
2010-09-24 19:18:45.075 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0xb12470 of class WebView autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.077 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2806790 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.077 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2806700 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.077 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2807480 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.078 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x283ff00 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.078 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2841df0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.078 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2841e50 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.078 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x2841bf0 of class NSCFArray autoreleased with no pool in place - just leaking
2010-09-24 19:18:45.079 bowline-desktop[3086:1c07] **\* __NSAutoreleaseNoPool(): Object 0x28415d0 of class __NSFastEnumerationEnumerator autoreleased with no pool in place - just leaking
localhost:helloworld Brad$ mate script

**Comment by os-hybrid** [comment]
Still getting the same results wit 0.9.4
