### ISSUE TITLE
Is Bowline abandoned?

### ISSUE THREAD

**Issue by drhenner** [maccman/bowline#28]
Just curious, are you planning to do any more work on this project?  If not why did you stop?  not enough traction?  node.js is more interesting?  Just wondering if it is worthwhile for this project to be supported by someone in the future.

**Comment by ghost** [comment]
I wonder the same.

**Comment by maccman** [comment]
Sorry, it pretty much is. If anyone wants to contribute, I'm happy to open up commit access.

I guess I gave it up in favor of JavaScript web applications. It's amazing what you can do nowadays in the browser with HTML5/CSS3 - I think it's the future. I'm currently writing a book for O'Reilly on the subject. 

I think it was the realization that JS could do all of the frontend really well (without involvement from Ruby), and that actually the language wasn't too bad ;)

If I was to build Bowline again, I'd take a very different approach by using MacRuby. As you can see from ichabod, it's very easy to use WebKit from Ruby - and expose Ruby objects to JavaScript - https://github.com/maccman/ichabod

When the application I'm currently developing comes to fruition, I may put something together on those lines - basically a MacRuby version of http://fluidapp.com/

Cheers,
Alex

**Comment by drhenner** [comment]
Thanks,

I'm a bit too busy to contribute.  Keep up the good work on juggernaut2 I'm more interested in that project.  Mountain West Ruby conf had a talk on desktop platforms and it had me wondering about this project.

Dave
www.ror-e.com
