### ISSUE TITLE
Source is not a class (TypeError)

### ISSUE THREAD

**Issue by pratikraj** [maccman/bowline#36]
After downloading this code and tried to execute command  "bowline-bundle install" I found error " .rvm/gems/ruby-1.9.2-p320/gems/bowline-bundler-0.0.4/lib/bowline/bundler/source.rb:6:in `module:Bundler': Source is not a class (TypeError)". Please help me.

I am using rails- 3.2.8, ruby ruby- 1.9.2p320 (2012-04-20 revision 35421) [i686-linux].

**Comment by zen0wu** [comment]
Same error here.
OS X Lion 10.7.4, rvm, ruby 1.9.3

**Comment by masterkain** [comment]
project is dead

**Comment by ranjithtenz** [comment]
Same issue here

**Comment by lance-ding** [comment]
Same issue here

**Comment by JoeWoo** [comment]
same issue here

**Comment by puti313** [comment]
same issue here. mac os x 10.6.8;rvm;ruby 1.9.2p320;

**Comment by JoeWoo** [comment]
@puti313 project is dead,the latest update at 2 years ago....maybe they don`t keep the project anymore.
