### ISSUE TITLE
Required gem 'json' is not installed by default

### ISSUE THREAD

**Issue by bigtiger** [maccman/bowline#4]
jremsikjr@pinto:~/hashrocket/app-of-bowline$ gem install bowline
    **************************************************

```
  Thank you for installing Bowline.

  If you're on Linux, please install the WebKit library:
    sudo apt-get install libwebkit-dev

**************************************************
```

Successfully installed diff-lcs-1.1.2
Successfully installed extlib-0.9.15
Successfully installed templater-1.0.0
Successfully installed i18n-0.3.7
Successfully installed tzinfo-0.3.22
Successfully installed builder-2.1.2
Successfully installed memcache-client-1.8.3
Successfully installed activesupport-3.0.0.beta3
Successfully installed rubyzip2-2.0.1
Successfully installed activemodel-3.0.0.beta3
Successfully installed supermodel-0.1.3
Successfully installed bowline-bundler-0.0.3
Successfully installed bowline-0.9.3
13 gems installed

jremsikjr@pinto:~/hashrocket$ bowline-gen app bow-test
/Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
    from /Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in `require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:195:in`load_dependency'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:523:in `new_constants_in'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:195:in`load_dependency'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in `require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/bowline-0.9.3/bin/../lib/bowline/desktop/bridge.rb:1
    from /Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in`require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:195:in `load_dependency'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:523:in`new_constants_in'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:195:in `load_dependency'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in`require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/bowline-0.9.3/bin/../lib/bowline.rb:37
    from /Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/jremsikjr/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/gems/bowline-0.9.3/bin/bowline-gen:3
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/bin/bowline-gen:19:in `load'
    from /Users/jremsikjr/.rvm/gems/ruby-1.8.7-p248@global/bin/bowline-gen:19
jremsikjr@pinto:~/hashrocket$ gem install json
Building native extensions.  This could take a while...
Successfully installed json-1.4.3
1 gem installed
jremsikjr@pinto:~/hashrocket$ bowline-gen app bow-test
Generating with app generator:
     [ADDED]  vendor
     [ADDED]  lib
... success!

**Comment by maccman** [comment]
Thanks for the heads up. The thing is, Ruby 1.9 includes json by default. I don't think I can add a gemspec dependency that targets a particular version of Ruby. In other words, Ruby 1.9 people would have an extra dependency that's not needed. The fact that's it's a c ext complicates things further. Let me know if I'm barking up the wrong tree, but in the mean time I'm going to close it.

**Comment by bigtiger** [comment]
Ahh, touche`, 1.9 being a dependency makes my point moot. Thanks for the quick response!
