### ISSUE TITLE
tzinfo required/fails with osx10.6(64bit)

### ISSUE THREAD

**Issue by fwoeck** [maccman/bowline#6]
ahh, I just read - 64bit is not supported - anyways, maybe just as a feedback:
even if I install tzinfo (ruby-1.9.1-p378, 64bit, osx10.63),
./script/run fails for a plain app with

You don't have tzinfo installed in your application. Please add it to your Gemfile and run bundle install
        no such file to load -- tzinfo

-- Frank

**Comment by maccman** [comment]
This problem has cropped up after the new Rails beta was released. I think tzinfo is an Activesupport dependency - get isn't in their gemspec. I'll open a ticket on the Rails lighthouse. In the mean time, just add tzinfo to your Gemfile.

**Comment by Soleone** [comment]
Hm, adding `gem "tzinfo"` did not change anything for me.

~/workspace/ruby/bowline-test ➜ bundle install
Fetching source index from http://rubygems.org/
^[Using activesupport (3.0.0.beta4) from bundler gems 
Using builder (2.1.2) from bundler gems 
Using i18n (0.4.1) from bundler gems 
Using activemodel (3.0.0.beta4) from bundler gems 
Using bowline-bundler (0.0.3) from bundler gems 
Using rubyzip2 (2.0.1) from bundler gems 
Using supermodel (0.1.3) from bundler gems 
Using diff-lcs (1.1.2) from bundler gems 
Using extlib (0.9.15) from bundler gems 
Using highline (1.5.2) from bundler gems 
Using templater (1.0.0) from bundler gems 
Using bowline (0.9.3) from bundler gems 
Using tzinfo (0.3.22) from bundler gems 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

~/workspace/ruby/bowline-test ➜ ./script/run
You don't have tzinfo installed in your application. Please add it to your Gemfile and run bundle install
    no such file to load -- tzinfo
/Users/soleone/workspace/ruby/bowline-test/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
[...]

**Comment by maccman** [comment]
Don't use 'bundle install'. As it says in the README, use bowline-bundle.

**Comment by Soleone** [comment]
Ah ok thanks, that solved the issue!
