### ISSUE TITLE
Faild to create new app

### ISSUE THREAD

**Issue by ghost** [maccman/bowline#7]
Faild to create new app on 64bit linux:

<pre><code>
$ bowline-gen app helloworld
You don't have tzinfo installed in your application. Please add it to your Gemfile and run bundle install
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require': no such file to load -- tzinfo (LoadError)
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/values/time_zone.rb:4:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/time_with_zone.rb:1:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/time/zones.rb:1:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/date/calculations.rb:3:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/string/conversions.rb:3:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activemodel-3.0.0.beta4/lib/active_model/observing.rb:5:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/supermodel-0.1.3/lib/supermodel/observing.rb:4:in `<module:Observing>'
    from /usr/lib/ruby/gems/1.9.1/gems/supermodel-0.1.3/lib/supermodel/observing.rb:2:in `<module:SuperModel>'
    from /usr/lib/ruby/gems/1.9.1/gems/supermodel-0.1.3/lib/supermodel/observing.rb:1:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/supermodel-0.1.3/lib/supermodel.rb:29:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/bowline-0.9.3/lib/bowline/app_config.rb:1:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /usr/lib/ruby/gems/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/bowline-0.9.3/lib/bowline.rb:55:in `<top (required)>'
    from /usr/lib/ruby/gems/1.9.1/gems/bowline-0.9.3/bin/bowline-gen:3:in `require'
    from /usr/lib/ruby/gems/1.9.1/gems/bowline-0.9.3/bin/bowline-gen:3:in `<top (required)>'
    from /usr/bin/bowline-gen:19:in `load'
    from /usr/bin/bowline-gen:19:in `<main>'
</code></pre>

**Comment by ghost** [comment]
on Mac too. (gem install tzinfo solves the problem)

**Comment by ghost** [comment]
I'm installed tzinfo, but another error happens:
<pre><code>$ ./script/run 
~/.bowline/bowline-desktop: error while loading shared libraries: libwebkit-1.0.so.2: wrong ELF class: ELFCLASS64</pre></code>
I have libwebkit 1.2.1-1 installed.

**Comment by maccman** [comment]
You need the 32 bit version of libwebkit. As for the tzinfo issue, search for the other ticket mentioning tzinfo, I explain it properly there.

**Comment by ghost** [comment]
Is 64 bit bowline planned? I think support for 64 bit platforms is very important.

**Comment by maccman** [comment]
Bowline is 32 bit and works fine on 64 bit platforms. If I compiled it at 64 bit then 32 bit platforms wouldn't work. As it stands, Bowline works on both architectures - you just need to have 32 bit libraries.

**Comment by ghost** [comment]
There is no 32 bit libwebkit on my distro and i have no any idea how to compile it. 
If i understand correct, it's possible to build bowline for both platforms. So, why you don't wont to maintain it for both of  them?
Supporting only 32 bit platforms brings problems for end users.

**Comment by maccman** [comment]
Well, I guess it's a trade off. I don't want users to have to choose 64/32 bit versions of the app, for each os, to download. Most end users won't understand what that is. Likewise, I don't want to ship universal binaries, since they'd be absolutely massive. So I decided to only distribute 32 bit versions of Bowline - since they work fine on both 32 and 64 bit platforms. I don't think that causes problems for end users. I do accept that that can cause problems for developers though (such as the one you're having with 32bit webkit). However, you could download webkit and compile it, right? http://webkit.org
Also, I'm happy to accept patches for 64bit compiled versions of bowline. I personally, however, will only be distributing 32 bit apps until the majority of people are using 64 bit OSes (for the reasons I mentioned above).
